from ._datatype import Datatype
from ._object import Object

class Literal(Object):
    def __init__(
        self,
        value: str,
        datatype: Datatype | None = None,
        language: str | None = None,
    ) -> None: ...
    def datatype(self) -> Datatype: ...
    def value(self) -> str: ...
    def language(self) -> str | None: ...
