from ._annotation import Annotation
from ._collection import Collection
from ._iri import IRI

class Object:
    def iri(self) -> IRI: ...
    def namespace(self) -> str: ...
    def remainder(self) -> str: ...
    def annotations(self) -> Collection[Annotation]: ...
