from pathlib import Path

from ._collection import Collection
from ._iri import IRI
from ._object import Object
from ._types import Axiom

class Ontology(Object):
    @classmethod
    def at_path(cls, path: Path | str) -> Ontology: ...
    def __init__(self) -> None: ...
    def axioms(self) -> Collection[Axiom]: ...
    def to_path(self, path: Path | str) -> None: ...
    def set_iri(self, iri: str | IRI) -> None: ...
    def add_axiom(self, axiom: Axiom) -> None: ...
    def remove_axiom(self, axiom: Axiom) -> None: ...
