from pathlib import Path

from ._axiom import Axiom
from ._collection import Collection
from ._object import Object

class Ontology(Object):
    @classmethod
    def at_path(cls, path: Path | str) -> Ontology: ...
    def axioms(self) -> Collection[Axiom]: ...
    def to_path(self, path: Path | str) -> None: ...
    def __init__(self) -> None: ...
