from collections.abc import (
    Callable,
    Collection as ABCCollection,
    Iterable,
    MutableMapping,
)
from enum import IntFlag, auto
from pathlib import Path
from typing import NoReturn, Protocol, overload

# Utilities

@overload
def one_of(*args: Individual) -> ObjectOneOf: ...
@overload
def one_of(*args: Literal | LiteralValue) -> DataOneOf: ...

# Protocols

class Annotated(Protocol):
    def annotations(self) -> Collection[Annotation]: ...

class HasIRI(Protocol):
    def iri(self) -> IRI: ...
    def namespace(self) -> str: ...
    def remainder(self) -> str: ...

class HasPrimitives(Protocol):
    def has_primitive(self, primitive: Primitive) -> bool: ...
    def foreach_primitive(self, func: Callable[[Primitive], None]) -> None: ...
    def primitives(self) -> Collection[Primitive]: ...

class PrimitiveFactory(Protocol):
    # ruff: disable[N802]
    def IRI(self, iri: str) -> IRI: ...
    def Class(self, iri: str | IRI) -> Class: ...
    def Datatype(self, iri: str | IRI) -> Datatype: ...
    def ObjectProperty(self, iri: str | IRI) -> ObjectProperty: ...
    def DataProperty(self, iri: str | IRI) -> DataProperty: ...
    def AnnotationProperty(self, iri: str | IRI) -> AnnotationProperty: ...
    def NamedIndividual(self, iri: str | IRI) -> NamedIndividual: ...
    def AnonymousIndividual(self, node_id: str | None = None) -> AnonymousIndividual: ...
    @overload
    def Individual(self, iri: str | IRI) -> NamedIndividual: ...
    @overload
    def Individual(self) -> AnonymousIndividual: ...
    # ruff: enable[N802]

# Enums

class Position(IntFlag):
    LEFT = auto()
    RIGHT = auto()
    MIDDLE = auto()

    ANY = LEFT | RIGHT | MIDDLE  # noqa: PYI026
    SUBJECT = LEFT
    PREDICATE = MIDDLE
    OBJECT = RIGHT

# Base types

class Object:
    def __init__(self) -> NoReturn: ...
    def is_entity(self) -> bool: ...
    def is_primitive(self) -> bool: ...
    def is_axiom(self) -> bool: ...
    def is_class_expression(self) -> bool: ...
    def is_data_range(self) -> bool: ...
    def is_object_property_expression(self) -> bool: ...
    def is_data_property_expression(self) -> bool: ...
    def is_individual(self) -> bool: ...

class Primitive(Object, HasPrimitives):
    def is_reserved(self) -> bool: ...

class Entity(Primitive, HasIRI): ...

class AnnotationProperty(Entity):
    def __init__(self, iri: str | IRI) -> None: ...

type AnnotationValue = IRI | Literal | AnonymousIndividual

class Annotation(Object, Annotated, HasPrimitives):
    def __init__(
        self,
        prop: AnnotationProperty,
        value: AnnotationValue,
    ) -> None: ...
    def prop(self) -> AnnotationProperty: ...
    def value(self) -> AnnotationValue: ...

class Collection[T: Object](Object, HasPrimitives, ABCCollection[T]):
    def __init__(self, *items: T) -> None: ...

class IRI(Primitive, HasIRI):
    def __init__(self, prefix: str, suffix: str | None = None) -> None: ...
    def as_string(self) -> str: ...

type LiteralValue = str | int | float | bool

class Literal(Object, HasPrimitives):
    @overload
    def __init__(
        self,
        value: LiteralValue,
        datatype: Datatype | None = None,
    ) -> None: ...
    @overload
    def __init__(
        self,
        value: str,
        language: str,
    ) -> None: ...
    def datatype(self) -> Datatype: ...
    def value(self) -> str: ...
    def language(self) -> str | None: ...

# Class expressions

class ClassExpression(Object, HasPrimitives):
    def __and__(self, other: ClassExpression) -> ObjectIntersectionOf: ...
    def __or__(self, other: ClassExpression) -> ObjectUnionOf: ...
    def __invert__(self: ClassExpression) -> ClassExpression: ...
    def is_a(self, other: ClassExpression) -> SubClassOf: ...
    def is_subclass_of(self, other: ClassExpression) -> SubClassOf: ...
    def is_equivalent_to(self, *others: ClassExpression) -> EquivalentClasses: ...
    def is_disjoint_with(self, *others: ClassExpression) -> DisjointClasses: ...
    def that(self, *args: ClassExpression) -> ObjectIntersectionOf: ...

class Class(ClassExpression, Entity):
    def __init__(self, iri: str | IRI) -> None: ...

class NAryBooleanClassExpression(ClassExpression):
    def __init__(self, *args: ClassExpression) -> None: ...
    def operands(self) -> Collection[ClassExpression]: ...

class ObjectIntersectionOf(NAryBooleanClassExpression): ...
class ObjectUnionOf(NAryBooleanClassExpression): ...

class ObjectComplementOf(ClassExpression):
    def __init__(self, operand: ClassExpression) -> None: ...
    def operand(self) -> ClassExpression: ...

class ObjectQuantifiedRestriction(ClassExpression):
    def __init__(self, prop: ObjectPropertyExpression, filler: ClassExpression) -> None: ...
    def prop(self) -> ObjectPropertyExpression: ...
    def filler(self) -> ClassExpression: ...

class ObjectSomeValuesFrom(ClassExpression): ...
class ObjectAllValuesFrom(ClassExpression): ...

class ObjectCardinalityRestriction(ClassExpression):
    def __init__(
        self,
        prop: ObjectPropertyExpression,
        cardinality: int,
        filler: ClassExpression | None = None,
    ) -> None: ...
    def prop(self) -> ObjectPropertyExpression: ...
    def cardinality(self) -> int: ...
    def filler(self) -> ClassExpression | None: ...

class ObjectMinCardinality(ObjectCardinalityRestriction): ...
class ObjectMaxCardinality(ObjectCardinalityRestriction): ...
class ObjectExactCardinality(ObjectCardinalityRestriction): ...

class ObjectOneOf(ClassExpression):
    def __init__(self, *inds: Individual) -> None: ...
    def individuals(self) -> Collection[Individual]: ...

class DataQuantifiedRestriction(ClassExpression):
    def __init__(self, prop: DataProperty, data_range: DataRange) -> None: ...
    def prop(self) -> DataProperty: ...
    def range(self) -> DataRange: ...

class DataSomeValuesFrom(ClassExpression): ...
class DataAllValuesFrom(ClassExpression): ...

class DataCardinalityRestriction(ClassExpression):
    def __init__(
        self,
        prop: DataProperty,
        cardinality: int,
        data_range: DataRange | None = None,
    ) -> None: ...
    def prop(self) -> DataProperty: ...
    def cardinality(self) -> int: ...
    def range(self) -> DataRange | None: ...

class DataMinCardinality(DataCardinalityRestriction): ...
class DataMaxCardinality(DataCardinalityRestriction): ...
class DataExactCardinality(DataCardinalityRestriction): ...

# Data ranges

class DataRange(Object, HasPrimitives):
    def __and__(self, other: DataRange) -> DataIntersectionOf: ...
    def __or__(self, other: DataRange) -> DataUnionOf: ...
    def __invert__(self: DataRange) -> DataRange: ...

class Datatype(DataRange, Entity):
    def __init__(self, iri: str | IRI) -> None: ...

class NAryDataRange(DataRange):
    def __init__(self, *args: DataRange) -> None: ...
    def operands(self) -> Collection[DataRange]: ...

class DataIntersectionOf(NAryDataRange): ...
class DataUnionOf(NAryDataRange): ...

class DataComplementOf(DataRange):
    def __init__(self, operand: DataRange) -> None: ...
    def operand(self) -> DataRange: ...

class DataOneOf(DataRange):
    def __init__(self, *values: Literal) -> None: ...
    def values(self) -> Collection[Literal]: ...

# Individuals

class Individual(Primitive):
    def is_a(self, cls: ClassExpression) -> ClassAssertion: ...

class NamedIndividual(Individual, Entity):
    def __init__(self, iri: str | IRI) -> None: ...

class AnonymousIndividual(Individual):
    def __init__(self, node_id: str | None = None) -> None: ...

# Object property expressions

class ObjectPropertyExpression(Object, HasPrimitives):
    def __call__(self, subj: Individual, obj: Individual) -> ObjectPropertyAssertion: ...
    def some(self, filler: ClassExpression) -> ObjectSomeValuesFrom: ...
    def all(self, filler: ClassExpression) -> ObjectAllValuesFrom: ...
    def min(
        self,
        cardinality: int,
        filler: ClassExpression | None = None,
    ) -> ObjectMinCardinality: ...
    def max(
        self,
        cardinality: int,
        filler: ClassExpression | None = None,
    ) -> ObjectMaxCardinality: ...
    def exactly(
        self,
        cardinality: int,
        filler: ClassExpression | None = None,
    ) -> ObjectExactCardinality: ...
    def has_domain(self, domain: ClassExpression) -> ObjectPropertyDomain: ...
    def has_range(self, prop_range: ClassExpression) -> ObjectPropertyRange: ...
    def is_functional(self) -> FunctionalObjectProperty: ...
    def is_inverse_functional(self) -> InverseFunctionalObjectProperty: ...
    def is_reflexive(self) -> ReflexiveObjectProperty: ...
    def is_irreflexive(self) -> IrreflexiveObjectProperty: ...
    def is_symmetric(self) -> SymmetricObjectProperty: ...
    def is_asymmetric(self) -> AsymmetricObjectProperty: ...
    def is_transitive(self) -> TransitiveObjectProperty: ...

class ObjectProperty(ObjectPropertyExpression, Entity):
    def __init__(self, iri: str | IRI) -> None: ...

class InverseObjectProperty(ObjectPropertyExpression):
    def __init__(self, prop: ObjectProperty) -> None: ...
    def prop(self) -> ObjectProperty: ...

# Data property expressions

class DataProperty(Entity):
    def __init__(self, iri: str | IRI) -> None: ...
    def __call__(
        self,
        subj: Individual,
        value: Literal | LiteralValue,
    ) -> DataPropertyAssertion: ...
    def some(self, data_range: DataRange) -> DataSomeValuesFrom: ...
    def all(self, data_range: DataRange) -> DataAllValuesFrom: ...
    def min(
        self,
        cardinality: int,
        data_range: DataRange | None = None,
    ) -> DataMinCardinality: ...
    def max(
        self,
        cardinality: int,
        data_range: DataRange | None = None,
    ) -> DataMaxCardinality: ...
    def exactly(
        self,
        cardinality: int,
        data_range: DataRange | None = None,
    ) -> DataExactCardinality: ...
    def has_domain(self, domain: ClassExpression) -> DataPropertyDomain: ...
    def has_range(self, prop_range: DataRange) -> DataPropertyRange: ...
    def is_functional(self) -> FunctionalDataProperty: ...

# Axioms

class Axiom(Object, Annotated, HasPrimitives): ...

class Declaration(Axiom):
    def __init__(
        self,
        entity: Entity,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...
    def entity(self) -> Entity: ...

class SubClassOf(Axiom):
    def __init__(
        self,
        sub_class: ClassExpression,
        super_class: ClassExpression,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...

class NAryClassAxiom(Axiom):
    def __init__(
        self,
        classes: Iterable[ClassExpression],
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...
    def classes(self) -> Collection[ClassExpression]: ...

class EquivalentClasses(NAryClassAxiom): ...
class DisjointClasses(NAryClassAxiom): ...

class ObjectPropertyAxiom(Axiom):
    def prop(self) -> ObjectPropertyExpression: ...

class ObjectPropertyDomain(ObjectPropertyAxiom):
    def __init__(
        self,
        prop: ObjectPropertyExpression,
        domain: ClassExpression,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...
    def domain(self) -> ClassExpression: ...

class ObjectPropertyRange(ObjectPropertyAxiom):
    def __init__(
        self,
        prop: ObjectPropertyExpression,
        prop_range: ClassExpression,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...
    def range(self) -> ClassExpression: ...

class ObjectPropertyCharacteristicAxiom(ObjectPropertyAxiom):
    def __init__(
        self,
        prop: ObjectPropertyExpression,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...

class FunctionalObjectProperty(ObjectPropertyCharacteristicAxiom): ...
class InverseFunctionalObjectProperty(ObjectPropertyCharacteristicAxiom): ...
class ReflexiveObjectProperty(ObjectPropertyCharacteristicAxiom): ...
class IrreflexiveObjectProperty(ObjectPropertyCharacteristicAxiom): ...
class SymmetricObjectProperty(ObjectPropertyCharacteristicAxiom): ...
class AsymmetricObjectProperty(ObjectPropertyCharacteristicAxiom): ...
class TransitiveObjectProperty(ObjectPropertyCharacteristicAxiom): ...

class DataPropertyAxiom(Axiom):
    def prop(self) -> DataProperty: ...

class DataPropertyDomain(DataPropertyAxiom):
    def __init__(
        self,
        prop: DataProperty,
        domain: ClassExpression,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...
    def domain(self) -> ClassExpression: ...

class DataPropertyRange(DataPropertyAxiom):
    def __init__(
        self,
        prop: DataProperty,
        prop_range: DataRange,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...
    def range(self) -> DataRange: ...

class FunctionalDataProperty(DataPropertyAxiom):
    def __init__(
        self,
        prop: DataProperty,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...

class ClassAssertion(Axiom):
    def __init__(
        self,
        cls: ClassExpression,
        ind: Individual,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...
    def class_expression(self) -> ClassExpression: ...
    def individual(self) -> Individual: ...

class ObjectPropertyAssertion(Axiom):
    def __init__(
        self,
        prop: ObjectPropertyExpression,
        subj: Individual,
        obj: Individual,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...
    def __invert__(self) -> ObjectPropertyAssertion: ...
    def prop(self) -> ObjectPropertyExpression: ...
    def subject(self) -> Individual: ...
    def object(self) -> Individual: ...

class NegativeObjectPropertyAssertion(ObjectPropertyAssertion): ...

class DataPropertyAssertion(Axiom):
    def __init__(
        self,
        prop: DataProperty,
        subj: Individual,
        value: Literal,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...
    def __invert__(self) -> DataPropertyAssertion: ...
    def prop(self) -> DataProperty: ...
    def subject(self) -> Individual: ...
    def value(self) -> Literal: ...

class NegativeDataPropertyAssertion(DataPropertyAssertion): ...

# Ontology

class Ontology(Object, Annotated, HasIRI, HasPrimitives, PrimitiveFactory):
    @classmethod
    def at_path(cls, path: Path | str) -> Ontology: ...
    @property
    def prefix_map(self) -> PrefixMap: ...
    def __init__(self) -> None: ...
    def __contains__(self, item: Axiom | Primitive) -> bool: ...
    def foreach_axiom(
        self,
        func: Callable[[Axiom], None],
        types: Iterable[type[Axiom]] | None = None,
        primitives: Iterable[Object] | None = None,
    ) -> None: ...
    def axioms(
        self,
        types: Iterable[type[Axiom]] | None = None,
        primitives: Iterable[Object] | None = None,
    ) -> Collection[Axiom]: ...
    def foreach_related(
        self,
        primitive: Primitive,
        axiom_type: type[Axiom],
        func: Callable[[Primitive], None],
        position: Position = ...,
    ) -> None: ...
    def related(
        self,
        primitive: Primitive,
        axiom_type: type[Axiom],
        position: Position = ...,
    ) -> Collection[Primitive]: ...
    def to_path(self, path: Path | str) -> None: ...
    def set_iri(self, iri: str | IRI, *, update_prefix: bool = False) -> None: ...
    def version(self) -> IRI | None: ...
    def set_version(self, version: str | IRI) -> None: ...
    def add(self, *args: Annotation | Axiom | IRI) -> None: ...
    def remove(self, *args: Annotation | Axiom | IRI) -> None: ...

class PrefixMap(Object, MutableMapping[str, str], PrimitiveFactory):
    @staticmethod
    def default() -> PrefixMap: ...
    def __init__(self) -> None: ...
    def items_iter(self) -> Iterable[tuple[str, str]]: ...

# Vocabularies

class OWL:
    PREFIX: str
    NS: str

    BACKWARD_COMPATIBLE_WITH: IRI
    DEPRECATED: IRI
    INCOMPATIBLE_WITH: IRI
    PRIOR_VERSION: IRI
    VERSION_INFO: IRI

    BOTTOM_DATA_PROPERTY: DataProperty
    BOTTOM_OBJECT_PROPERTY: ObjectProperty
    NOTHING: Class
    RATIONAL: Datatype
    REAL: Datatype
    THING: Class
    TOP_DATA_PROPERTY: DataProperty
    TOP_OBJECT_PROPERTY: ObjectProperty

class RDF:
    PREFIX: str
    NS: str

    LANG_RANGE: IRI

    LANG_STRING: Datatype
    PLAIN_LITERAL: Datatype
    XML_LITERAL: Datatype

class RDFS:
    PREFIX: str
    NS: str

    COMMENT: IRI
    IS_DEFINED_BY: IRI
    LABEL: IRI
    SEE_ALSO: IRI

    LITERAL: Datatype

class XSD:
    PREFIX: str
    NS: str

    LENGTH: IRI
    MAX_EXCLUSIVE: IRI
    MAX_INCLUSIVE: IRI
    MAX_LENGTH: IRI
    MIN_EXCLUSIVE: IRI
    MIN_INCLUSIVE: IRI
    MIN_LENGTH: IRI
    PATTERN: IRI

    ANY_URI: Datatype
    BASE64_BINARY: Datatype
    BOOLEAN: Datatype
    BYTE: Datatype
    DATE_TIME: Datatype
    DATE_TIME_STAMP: Datatype
    DECIMAL: Datatype
    DOUBLE: Datatype
    FLOAT: Datatype
    HEX_BINARY: Datatype
    INT: Datatype
    INTEGER: Datatype
    LANGUAGE: Datatype
    LONG: Datatype
    NAME: Datatype
    NCNAME: Datatype
    NEGATIVE_INTEGER: Datatype
    NMTOKEN: Datatype
    NON_NEGATIVE_INTEGER: Datatype
    NON_POSITIVE_INTEGER: Datatype
    NORMALIZED_STRING: Datatype
    POSITIVE_INTEGER: Datatype
    SHORT: Datatype
    STRING: Datatype
    TOKEN: Datatype
    UNSIGNED_BYTE: Datatype
    UNSIGNED_INT: Datatype
    UNSIGNED_LONG: Datatype
    UNSIGNED_SHORT: Datatype
