from collections.abc import Collection as ABCCollection, Iterable, Iterator
from pathlib import Path

from ._types import (
    AnnotationValue,
    Primitive,
)

# Base types

class Object:
    def iri(self) -> IRI: ...
    def namespace(self) -> str: ...
    def remainder(self) -> str: ...
    def annotations(self) -> Collection[Annotation]: ...
    def is_reserved(self) -> bool: ...
    def has_primitive(self, primitive: Primitive) -> bool: ...
    def primitives(self) -> Collection[Primitive]: ...

class AnnotationProperty(Object):
    def __init__(self, iri: str | IRI) -> None: ...

class Annotation(Object):
    def __init__(
        self,
        prop: AnnotationProperty,
        value: AnnotationValue,
    ) -> None: ...
    def property(self) -> AnnotationProperty: ...
    def value(self) -> AnnotationValue: ...

class Collection[T: Object](Object, ABCCollection[T]):
    def __init__(self, items: Iterable[T]) -> None: ...

class DataProperty(Object):
    def __init__(self, iri: str | IRI) -> None: ...

class Datatype(Object):
    def __init__(self, iri: str | IRI) -> None: ...

class IRI(Object):
    def __init__(self, prefix: str, suffix: str | None = None) -> None: ...
    def as_string(self) -> str: ...

class Literal(Object):
    def __init__(
        self,
        value: str,
        datatype: Datatype | None = None,
        language: str | None = None,
    ) -> None: ...
    def datatype(self) -> Datatype: ...
    def value(self) -> str: ...
    def language(self) -> str | None: ...

# Class expressions

class ClassExpression(Object):
    def __and__(self, other: ClassExpression) -> ObjectIntersectionOf: ...
    def __or__(self, other: ClassExpression) -> ObjectUnionOf: ...
    def is_a(self, other: ClassExpression) -> SubClassOf: ...

class Class(ClassExpression):
    def __init__(self, iri: str | IRI) -> None: ...

class ObjectIntersectionOf(ClassExpression):
    def __init__(self, *args: ClassExpression) -> None: ...
    def operands(self) -> Collection[ClassExpression]: ...

class ObjectUnionOf(ClassExpression):
    def __init__(self, *args: ClassExpression) -> None: ...
    def operands(self) -> Collection[ClassExpression]: ...

class ObjectAllValuesFrom(ClassExpression):
    def __init__(self, prop: ObjectPropertyExpression, filler: ClassExpression) -> None: ...
    def property(self) -> ObjectPropertyExpression: ...
    def filler(self) -> ClassExpression: ...

class ObjectSomeValuesFrom(ClassExpression):
    def __init__(self, prop: ObjectPropertyExpression, filler: ClassExpression) -> None: ...
    def property(self) -> ObjectPropertyExpression: ...
    def filler(self) -> ClassExpression: ...

# Individuals

class Individual(Object):
    def is_a(self, cls: ClassExpression) -> ClassAssertion: ...

class NamedIndividual(Individual):
    def __init__(self, iri: str | IRI) -> None: ...

class AnonymousIndividual(Individual):
    def __init__(self, node_id: str | None = None) -> None: ...

# Object property expressions

class ObjectPropertyExpression(Object):
    def some(self, filler: ClassExpression) -> ObjectSomeValuesFrom: ...
    def all(self, filler: ClassExpression) -> ObjectAllValuesFrom: ...

class ObjectProperty(ObjectPropertyExpression):
    def __init__(self, iri: str | IRI) -> None: ...

class InverseObjectProperty(ObjectPropertyExpression):
    def __init__(self, prop: ObjectProperty) -> None: ...
    def property(self) -> ObjectProperty: ...

# Axioms

class Axiom(Object): ...

class SubClassOf(Axiom):
    def __init__(
        self,
        sub_class: ClassExpression,
        super_class: ClassExpression,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...

class ClassAssertion(Axiom):
    def __init__(
        self,
        cls: ClassExpression,
        ind: Individual,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...
    def class_expression(self) -> ClassExpression: ...
    def individual(self) -> Individual: ...

# Ontology

class Ontology(Object):
    @classmethod
    def at_path(cls, path: Path | str) -> Ontology: ...
    @property
    def prefix_map(self) -> PrefixMap: ...
    def __init__(self) -> None: ...
    def __contains__(self, item: Axiom | Primitive) -> bool: ...
    def axioms(self) -> Collection[Axiom]: ...
    def to_path(self, path: Path | str) -> None: ...
    def set_iri(self, iri: str | IRI, *, update_prefix: bool = False) -> None: ...
    def set_version(self, version: str | IRI) -> None: ...
    def add(self, *args: Annotation | Axiom | IRI) -> None: ...
    def remove(self, *args: Annotation | Axiom | IRI) -> None: ...

class PrefixMap(Object):
    @staticmethod
    def default() -> PrefixMap: ...
    def __init__(self) -> None: ...
    def __setitem__(self, prefix: str, ns: str) -> None: ...
    def __getitem__(self, prefix_or_ns: str) -> str: ...
    def __delitem__(self, prefix_or_ns: str) -> None: ...
    def __len__(self) -> int: ...
    def add(self, prefix: str, ns: str) -> None: ...
    def remove(self, prefix_or_ns: str) -> None: ...
    def get(self, prefix_or_ns: str) -> str | None: ...
    def items(self) -> Iterator[tuple[str, str]]: ...
    def prefixes(self) -> Iterator[str]: ...
    def namespaces(self) -> Iterator[str]: ...
