from collections.abc import Collection as ABCCollection, Iterable
from pathlib import Path

from ._types import AnnotationValue, Axiom, ClassExpression

# Base types

class Object:
    def iri(self) -> IRI: ...
    def namespace(self) -> str: ...
    def remainder(self) -> str: ...
    def annotations(self) -> Collection[Annotation]: ...

class AnnotationProperty(Object):
    def __init__(self, iri: str | IRI) -> None: ...

class Annotation(Object):
    def __init__(
        self,
        prop: AnnotationProperty,
        value: AnnotationValue,
    ) -> None: ...
    def property(self) -> AnnotationProperty: ...
    def value(self) -> AnnotationValue: ...

class AnonymousIndividual(Object):
    def __init__(self, node_id: str | None = None) -> None: ...

class Class(Object):
    def __init__(self, iri: str | IRI) -> None: ...

class Collection[T: Object](Object, ABCCollection[T]):
    def __init__(self, items: Iterable[T]) -> None: ...

class DataProperty(Object):
    def __init__(self, iri: str | IRI) -> None: ...

class Datatype(Object):
    def __init__(self, iri: str | IRI) -> None: ...

class IRI(Object):
    def __init__(self, prefix: str, suffix: str | None = None) -> None: ...

class Literal(Object):
    def __init__(
        self,
        value: str,
        datatype: Datatype | None = None,
        language: str | None = None,
    ) -> None: ...
    def datatype(self) -> Datatype: ...
    def value(self) -> str: ...
    def language(self) -> str | None: ...

class NamedIndividual(Object):
    def __init__(self, iri: str | IRI) -> None: ...

class ObjectProperty(Object):
    def __init__(self, iri: str | IRI) -> None: ...

# Class expressions

class ObjectIntersectionOf(Object):
    def __init__(self, operands: Iterable[ClassExpression]) -> None: ...
    def operands(self) -> Collection[ClassExpression]: ...

# Axioms

class SubClassOf(Object):
    def __init__(
        self,
        sub_class: ClassExpression,
        super_class: ClassExpression,
        annotations: Iterable[Annotation] | None = None,
    ) -> None: ...

# Ontology

class Ontology(Object):
    @classmethod
    def at_path(cls, path: Path | str) -> Ontology: ...
    def __init__(self) -> None: ...
    def axioms(self) -> Collection[Axiom]: ...
    def to_path(self, path: Path | str) -> None: ...
    def set_iri(self, iri: str | IRI) -> None: ...
    def add_axiom(self, axiom: Axiom) -> None: ...
    def remove_axiom(self, axiom: Axiom) -> None: ...
