from .primitive import Primitive

class IRI(Primitive):
    @property
    def namespace(self) -> str: ...
    @property
    def remainder(self) -> str: ...
    def __init__(self, prefix: str, suffix: str | None = None) -> None: ...
