from .annotation import Annotation
from .collection import Collection
from .iri import IRI

class Object:
    def iri(self) -> IRI: ...
    def namespace(self) -> str: ...
    def remainder(self) -> str: ...
    def annotations(self) -> Collection[Annotation]: ...
