from pathlib import Path

from .axiom import Axiom
from .collection import Collection
from .object import Object

class Ontology(Object):
    @classmethod
    def at_path(cls, path: Path | str) -> Ontology: ...
    def get_axioms(self) -> Collection[Axiom]: ...
    def to_path(self, path: Path | str) -> None: ...
    def __init__(self) -> None: ...
