from pathlib import Path

from .collection import Collection
from .object import Object

class Ontology(Object):
    @classmethod
    def empty(cls) -> Ontology: ...
    @classmethod
    def at_path(cls, path: Path | str) -> Ontology: ...
    def get_axioms(self) -> Collection[Object]: ...
    def to_path(self, path: Path | str) -> None: ...
