[project]
name = "cowl"
description = "A Python library for working with OWL 2 ontologies"
version = "0.1.0"
authors = [
    { name = "Ivano Bilenchi", email = "ivano.bilenchi@poliba.it" },
    { name = "Davide Loconte", email = "davide.loconte@poliba.it" },
]
license = "EPL-2.0"
license-files = ["LICENSE"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12"
dependencies = []

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
Homepage = "https://swot.sisinflab.poliba.it/pycowl"

[build-system]
requires = ["setuptools>=61.0.0", "cython"]
build-backend = "setuptools.build_meta"

[tool.cython-lint]
max-line-length = 100

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "BLE001",  # blind-except
    "D203",    # one-blank-line-before-class
    "D212",    # multi-line-summary-first-line
    "D418",    # overload-with-docstring
    "PD",      # pandas
    "PLC0414", # useless-import-alias
    "PLR09",   # too-many-*
    "PYI021",  # docstring-in-stub
]
isort.combine-as-imports = true
[tool.ruff.lint.per-file-ignores]
"!src/*.py" = [
    "D",       # docstrings
    "PLR2004", # magic-value-comparison
    "S101",    # assert
    "T201",    # print
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
cowl = ["*.so", "*.dylib", "*.dll"]

[tool.setuptools.exclude-package-data]
cowl = ["*.c"]
