[project]
name = "pycowl"
description = "A Python library for working with Web Ontology Language (OWL) ontologies"
authors = [
    { name = "Ivano Bilenchi", email = "ivano.bilenchi@poliba.it" },
    { name = "Davide Loconte", email = "davide.loconte@poliba.it" },
]
license = "EPL-2.0"
license-files = ["LICENSE"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12"
dependencies = ["typing-extensions; python_version < '3.14'"]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
pycowl = "cowl._cli:app"

[project.urls]
Homepage = "https://github.com/sisinflab-swot/pycowl"
Repository = "https://github.com/sisinflab-swot/pycowl"
Download = "https://github.com/sisinflab-swot/pycowl/releases"
Changelog = "https://github.com/sisinflab-swot/pycowl/blob/master/CHANGELOG.md"

[build-system]
requires = ["scikit-build-core", "cython", "cython-cmake"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
build-dir = "build/{wheel_tag}"
sdist.include = ["src/cowl/_version.py"]
wheel.packages = ["src/cowl"]
wheel.exclude = ["**.pyx"]

[tool.setuptools_scm]
version_file = "src/cowl/_version.py"

[tool.cython-lint]
max-line-length = 100

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "BLE001",  # blind-except
    "D203",    # one-blank-line-before-class
    "D212",    # multi-line-summary-first-line
    "D418",    # overload-with-docstring
    "PD",      # pandas
    "PLC0414", # useless-import-alias
    "PLR09",   # too-many-*
    "PYI021",  # docstring-in-stub
]
isort.combine-as-imports = true

[tool.ruff.lint.per-file-ignores]
"!src/*.py" = [
    "D",       # docstrings
    "PLR2004", # magic-value-comparison
    "S101",    # assert
    "T201",    # print
]
